routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

// Auth::routes();
Route::get('/admin/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/admin/login', 'Auth\LoginController@login');
Route::post('/admin/logout', 'Auth\LoginController@logout')->name('logout');
// Registration Routes
Route::get('/admin/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/admin/register', 'Auth\RegisterController@register');
// Password Reset Routes
Route::get('/admin/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/admin/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/admin/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('/admin/password/reset', 'Auth\ResetPasswordController@reset');
// Admin Dashboard Route
Route::get('/admin/home', 'HomeController@index')->middleware('auth')->name('home');
// Logout Route
Route::get('/admin/logout', 'Auth\LoginController@logout', function(){
	return view('index')->with('success','You have been logged out of your account.');
});
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/home', 'HomeController@index')->name('home');

//tables
Route::get('/tables/services', 'TablesController@services')->middleware('auth');
Route::get('/tables/reservations', 'TablesController@reservations')->middleware('auth');

//dropdowns
Route::get('/lists/services', 'DropdownsController@services');

//services
Route::resource('/services', 'ServicesController');

//reservations
Route::get('/reservations', 'ReservationsController@index')->middleware('auth');
Route::get('/reservations/view/{reservation}', 'ReservationsController@show');
Route::post('/reservations/place-reservation', 'ReservationsController@store');
Route::delete('/reservations/{reservation}', 'ReservationsController@destroy')->name('reservations.destroy')->middleware('auth');
Route::put('/reservations/{reservation}', 'ReservationsController@update')->name('reservations.update')->middleware('auth');
Route::get('/reservations/{reservation}/receipt', 'ReportsController@reservation_receipt');
Route::get('/reservations/place-reservation/successful', function(){
	return redirect('/')->with('status','Reservation placement successful.');
});
Route::get('/reservations/place-reservation/failed', function(){
	return redirect('/')->with('status','Reservation placement failed.');
});
Route::get('/reservations/count', 'ReservationsController@count')->middleware('auth');

//SMS Notifications using Nexmo SMS API
// Route::get('/sms/send/{number}/{name}/{date}', function(\Nexmo\Client $nexmo, $number, $name, $date) {
// 	$message = $nexmo->message()->send([
// 		'to' => $number,
// 		'from' => '@leggetter',
// 		'text' => 'Hello, '.$name.' Sent at '.$date
// 	]);
// 	Log::info('sent message: ' . $message['message-id']);

// 	return 'Message '.$message['message-id'].' successfully sent.';

// });

//reports
Route::get('/reports/reservations', 'ReportsController@reservations')->middleware('auth');

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $fillable = [
    	"txt-service-desc",
    	"nud-service-price"
    ];
}

app/Http/Controllers/ServicesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Service;

class ServicesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.services.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $service = new Service;
        $service->desc = $request["txt-service-desc"];
        $service->price = $request["nud-service-price"];
        $service->save();

        return redirect('/services')->with('success','Service added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $service = Service::find($id);

        return view('admin.services.view')->with('service',$service);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $service = Service::find($id);
        $service->delete();

        return redirect('/services')->with('success','Delete successful.');
    }
}

resources/views/admin/services/index.blade.php
@section('page-name')
    {{ config('app.name', 'Cannot display page name') }} | Services
@endsection

@extends('layouts.master')

@section('content')
    <div class = "row">
        <div class = "seven wide column">
            <div class = "ui small raised text segment">
                <h5 class = "ui header">Add service</h5>

                <form id = "frm-add-service" class = "ui small equal width form" action = "{{ route('services.store') }}" method = "post">
                    {{ csrf_field() }}

                    <div class = "field{{ $errors->has('txt-service-desc') ? ' has-txt-service-desc' : '' }}">
                        <label>Description:</label>
                        <input type = "text" id = "txt-service-desc" name = "txt-service-desc" required autofocus>
                    </div>

                    <div class = "field{{ $errors->has('txt-service-price') ? ' has-txt-service-price' : '' }}">
                        <label>Price:</label>
                        <input type = "number" id = "nud-service-price" name = "nud-service-price" min = "0.00" step = "0.01" required>
                    </div>

                    <button type = "submit" id = "btn-add-service" name = "btn-add-service" class = "ui small positive button">
                        <i class = "send icon"></i>
                        Submit
                    </button>
                </form>
            </div>
        </div>

        <div class = "column">
            <div class = "ui small raised text segment">
                <h5 class = "ui header">List of services</h5>

                <table id = "tblListOfServices" class = "ui small celled striped table" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Description</th>
                            <th>Price</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    @if($errors->has('txt-service-desc'))
        <script type = "text/javascript">
            toastr.error('{{ $errors->first('txt-service-desc') }}');
        </script>
    @endif

    @if($errors->has('nud-service-price'))
        <script type = "text/javascript">
            toastr.error('{{ $errors->first('nud-service-price') }}');
        </script>
    @endif

    @if(session()->has('success'))
        <script type = "text/javascript">
            toastr.success('{{ session('success') }}');
        </script>
    @endif

    <script type = "text/javascript">
        $('#pgServices').toggleClass('active',true);
    </script>
@endsection

resources/views/admin/services/view.blade.php
@section('page-name')
    {{ config('app.name', 'Cannot display page name') }} | Services
@endsection

@extends('layouts.master')

@section('content')
    <div class = "row">
        <div class = "column"></div>

        <div class = "ten wide column">
            <div class = "ui small raised text segment">
                <h5 class = "ui header">Edit service</h5>

                <form id = "frmDeleteService" action = "{{ route('services.destroy', $service->id) }}" method = "post" hidden>
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                </form>

                <form id = "frm-add-service" class = "ui small equal width form" action = "{{ route('services.update', $service->id) }}" method = "post">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}

                    <div class = "field{{ $errors->has('txt-service-desc') ? ' has-txt-service-desc' : '' }}">
                        <label>Description:</label>
                        <input type = "text" id = "txt-service-desc" name = "txt-service-desc" value = "{{ $service->desc }}" required autofocus>
                    </div>

                    <div class = "field{{ $errors->has('txt-service-price') ? ' has-txt-service-price' : '' }}">
                        <label>Price:</label>
                        <input type = "number" id = "nud-service-price" name = "nud-service-price" value = "{{ $service->price }}" min = "0.00" step = "0.01" required>
                    </div>

                    <div class = "ui three small buttons">
                        <a href = "/services" role = "button" class = "ui button">
                            <i class = "arrow left icon"></i>
                            Back
                        </a>

                        <button type = "submit" class = "ui positive button">
                            <i class = "send icon"></i>
                            Edit
                        </button>

                        <button type = "button" class = "ui negative button" onclick = "$('#frmDeleteService').submit()">
                            <i class = "trash icon"></i>
                            Delete
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <div class = "column"></div>
    </div>
@endsection

@section('scripts')
    @if($errors->has('txt-service-desc'))
        <script type = "text/javascript">
            toastr.error('{{ $errors->first('txt-service-desc') }}');
        </script>
    @endif

    @if($errors->has('nud-service-price'))
        <script type = "text/javascript">
            toastr.error('{{ $errors->first('nud-service-price') }}');
        </script>
    @endif

    @if(session()->has('success'))
        <script type = "text/javascript">
            toastr.success('{{ session('success') }}');
        </script>
    @endif

    <script type = "text/javascript">
        $('#pgServices').toggleClass('active',true);
    </script>
@endsection